model_architecture:
    random_seed: 1
    neuron_activity:
        goal: 0.2
        force: 10
    transmission_delay:
        min: 5
        max: 20
    short_term_memory:
        capacity: 200
        appendage:
            frequency: 40
            max_size: 5
    long_term_memory:
        capacity: 200
        appendage:
            frequency: 200
            max_size: 5