model:
    random_seed: 1

    fnn_hidden_size_deviation: 32

    neuron_activity:
        goal: 0.2
        force: 10

    transmission_delay:
        min: 5
        max: 20

    memory:
        block_capacity: 16
        appendage_frequency: 40
        block_fnn: [ 256, 256, 256 ]

    levels:
        -   graph: crossed-box
            latent_dim: 1024
            buffer_size: 4096
            memory_size: 2048
            composition_fnn: [ 1024, 1024, 1024 ]
            decomposition_fnn: [ 1024, 1024, 1024 ]

        -   graph: crossed-box
            latent_dim: 512
            buffer_size: 2048
            memory_size: 1024
            composition_fnn: [ 1024, 1024, 1024 ]
            decomposition_fnn: [ 1024, 1024, 1024 ]

        -   graph: crossed-box
            latent_dim: 256
            buffer_size: 1024
            memory_size: 512
            composition_fnn: [ 512, 1024, 512 ]
            decomposition_fnn: [ 512, 1024, 512 ]

    primitive_neuron_fnn: [ 512, 1024, 1024, 512 ]